config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/pins'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def users
  end

  def faq
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>

<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
  </head>

    <body>
      <header>
     <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          
          <%= link_to image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/67107-200.png", width:'30', height:'30', class: "img-fluid"), root_path, class:'navbar-brand' %>
        
        </div>
        
          <ul class="nav navbar-nav">
             <li class="<%= 'active' if current_page?(welcome_index_path) %>"><%= link_to "Home", welcome_index_path %> 
             </li>
             <li class="<%= 'active' if current_page?(welcome_pins_path) %>"><%= link_to "Pins", welcome_pins_path %> 
             </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search"> 
                </div>
              <button type="submit" class="btn btn-default">Buscar</button>
              </form>
            </li>
            <li class="divider"></li>
            <form class="navbar-form navbar-right" role="search">
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></button>
              </form>
          </ul>
        
            
        
      </div>
     </nav>
     </header>

        <div class="container">
          <%= yield %>
        </div>
    </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome</h1>
  <h2>Bienvenido!</h2>
</div>

<div class="starter-template">
<p>
Lorem ipsum dolor sit amet consectetur adipiscing elit blandit sodales, facilisi vivamus primis dignissim purus curabitur ante. Torquent ante luctus cum dictumst laoreet commodo turpis eget nibh egestas odio, pulvinar potenti neque auctor nec ac elementum nam convallis tempus mi, cubilia nullam a etiam feugiat est vestibulum vel molestie sapien. Sem duis hac nullam augue nostra enim rutrum, pulvinar natoque eros pharetra semper vulputate, cum eleifend vivamus turpis potenti mauris. Volutpat risus ornare est sed cras sagittis duis ullamcorper nunc, ante nullam egestas conubia auctor dictum nascetur cum euismod ultrices, et potenti vivamus etiam vel facilisis mattis dapibus. Sodales fusce ornare potenti posuere suspendisse convallis felis, magna et cubilia habitasse nascetur pulvinar ad, nullam maecenas varius rhoncus rutrum conubia. Sapien cras lobortis aptent parturient ullamcorper conubia, pulvinar vitae habitant eu mi, natoque euismod porttitor erat sociosqu. Ornare ultricies gravida quis sollicitudin blandit bibendum donec ullamcorper, class himenaeos odio velit potenti sagittis habitant eget, ridiculus dis curabitur phasellus conubia aliquam libero.
</p>
<p>
Aenean dictum tempus nascetur consequat urna parturient, ligula cursus massa euismod mi vivamus, neque vulputate porta lacus malesuada. Taciti primis senectus euismod hendrerit class, duis lobortis nec porttitor non, quam rutrum nam at. Mollis odio himenaeos cursus nascetur natoque feugiat nec auctor condimentum, turpis vulputate suspendisse vivamus donec eu nibh platea sociosqu arcu, placerat tempus egestas libero porttitor ridiculus felis fringilla. Eros sapien libero bibendum tortor nam consequat purus rhoncus duis, dictum risus viverra montes nisi nibh odio turpis, orci ornare potenti lacinia id aptent praesent porta. Magna pulvinar consequat nostra tempor tempus porta mollis nullam metus dis, netus mus commodo scelerisque sociis ligula litora lacinia ante vitae, rhoncus sociosqu curabitur luctus neque ultrices suscipit etiam integer. Et magnis senectus sagittis commodo felis rhoncus sapien condimentum sem nam, dictumst libero vivamus at mollis potenti erat vulputate per, vehicula dignissim pulvinar orci eu quam augue justo sed. Cubilia ut nec magna cum varius convallis risus, vitae taciti posuere blandit quisque pretium sociis, dictumst id lobortis parturient ornare condimentum.
</p>
</div>

app/views/welcome/pins.html.erb
<div class="jumbotron text-center">
  <h1>Pins Guardados</h1>
</div>

<div class="starter-template">

		<div class="container">
			<div class="row">
				<div class="col-md-4">

				  <img src="https://i.pinimg.com/originals/cf/07/d5/cf07d51d11dae0cb12f882d2d61e3478.jpg" alt="Helmet" 
				  class='img-responsive'>
				  <img src="https://cdn.20m.es/img2/recortes/2018/03/08/653665-600-338.jpg" alt="PS4" 
				  class='img-responsive'>
				</div>

				<div class="col-md-4">
				  <img src="http://mouse.latercera.com/wp-content/uploads/2018/03/goku.jpg" alt="DBZ" 
				  class='img-responsive'>
			  	<img src="https://i.pinimg.com/736x/c1/df/ae/c1dfaeaeda06b3a3337dd1d8b6be3cd2--the-strokes-sticker.jpg" alt="TheStrokes" 
				  class='img-responsive'>

				</div>

				<div class="col-md-4">
				  <img src="https://www.bmw.com.mx/content/dam/bmw/common/topics/fascination-bmw/BMWi/2016/bmw-i-visions/BMWi-i3-Brand-OPC-visions-timeline-02.jpg/_jcr_content/renditions/cq5dam.resized.img.585.low.time1462167627367.jpg" alt="BMW" 
				  class='img-responsive'>
					<img src="https://vignette.wikia.nocookie.net/kong/images/f/f0/Gorillaz_plastic_beach_logo_render_by_noodlekyuzo-d5gjdte.png/revision/latest?cb=20160804190647" alt="Gorillaz" 
				  class='img-responsive'>
				  
				</div>

				<div class="col-md-4">
				  <img src="https://images.ctfassets.net/cgytwpzevc5f/1uvdWNPeZG20coiaU6kIeG/ee92419328d82a58ab226fd1872c243e/Scrambler-Classic-White-Model-MY18-01-780x430.jpg" alt="Moto" 
				  class='img-responsive'>
				</div>


			</div>

		</div>